ASPNetMongoDB/Models/Cat.cs
namespace ASPNetMongoDB.Models;

using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

public class Cat
{
    /// <summary>Kattens Id på MongoDB.</summary>
    [BsonId]
    [BsonRepresentation(BsonType.ObjectId)]
    public string Id { get; set; } = "";

    /// <summary>Kattens namn.</summary>
    public string Name { get; set; } = "";

    /// <summary>Kattens färg.</summary>
    public string Color { get; set; } = "";
}

ASPNetMongoDB/Models/ErrorViewModel.cs
namespace ASPNetMongoDB.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

ASPNetMongoDB/Controllers/CatsController.cs
namespace ASPNetMongoDB.Controllers;

using ASPNetMongoDB.Database;
using ASPNetMongoDB.Models;
using Microsoft.AspNetCore.Mvc;

public class CatsController : Controller
{
    #region Private Fields

    //Deklarerar en privat fält av typen MongoDBContext
    private readonly MongoDBContext _mongoDBContext;

    #endregion Private Fields

    #region Public Constructors

    //Konstruktorn instansierar en ny MongoDBContext och sätter det som vårt privata fält
    public CatsController() => _mongoDBContext = new MongoDBContext();

    #endregion Public Constructors

    #region Public Methods

    //HttpGet metod för att skapa en ny katt
    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }

    //HttpPost metod för att skapa en ny katt, tar emot ett Cat-objekt från vyn
    [HttpPost]
    public IActionResult Create(Cat cat)
    {
        //Använder vår MongoDBContext för att skapa en ny katt i databasen
        _mongoDBContext.CreateCat(cat);
        //Redirect till index-sidan efter att katten skapats
        return RedirectToAction("Index");
    }

    //HttpPost metod för att radera en befintlig katt, tar emot en id som parameter
    [HttpGet]
    public IActionResult Delete(string id)
    {
        //Använder vår MongoDBContext för att radera en katt i databasen
        _mongoDBContext.DeleteCat(id);
        //Redirect till index-sidan efter att katten raderats
        return RedirectToAction("Index");
    }

    //HttpGet metod för att hämta detaljer för en katt, tar emot en id som parameter
    [HttpGet]
    public IActionResult Details(string id)
    {
        //Använder vår MongoDBContext för att hämta en katt med det angivna id:t
        var cat = _mongoDBContext.GetCat(id);
        return View(cat);
    }

    //HttpGet metod för att redigera en befintlig katt, tar emot en id som parameter
    [HttpGet]
    public IActionResult Edit(string id)
    {
        //Använder vår MongoDBContext för att hämta en katt med det angivna id:t
        var cat = _mongoDBContext.GetCat(id);
        return View(cat);
    }

    //HttpPost metod för att uppdatera en befintlig katt, tar emot ett Cat-objekt från vyn
    [HttpPost]
    public IActionResult Edit(Cat cat)
    {
        //Använder vår MongoDBContext för att uppdatera en katt i databasen
        _mongoDBContext.UpdateCat(cat.Id, cat);
        //Redirect till index-sidan efter att katten uppdaterats
        return RedirectToAction("Index");
    }

    // HttpGet-metod som hämtar alla katter från databasen och returnerar dem till vyn.
    [HttpGet]
    public IActionResult Index()
    {
        //Använder vår MongoDBContext för att hämta alla katter
        var cats = _mongoDBContext.GetAllCats();
        return View(cats);
    }

    #endregion Public Methods
}

ASPNetMongoDB/Controllers/HomeController.cs
namespace ASPNetMongoDB.Controllers;

using ASPNetMongoDB.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

ASPNetMongoDB/Views/Cats/Create.cshtml
@model Cat

@{
    ViewData["Title"] = "Skapa";
}

<h1>Skapa en ny katt</h1>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>Katt</h4>
        <hr />
        <!-- Detta är fältet där du kan skriva in kattens namn -->
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>

        <!-- Detta är fältet där du kan välja färgen på katten -->
        <div class="form-group">
            <label asp-for="Color" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Color" class="form-control" />
                <span asp-validation-for="Color" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Skapa" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Tillbaka till listan</a>
</div>

ASPNetMongoDB/Views/Cats/Details.cshtml
@model Cat
@{
    ViewData["Title"] = "Detaljer på en katt";
}
<h1>Kattinformation</h1>

<div class="row">
    <div class="col-md-2">
        <h4>Katt</h4>
        <hr />
        <div>
            <dl class="dl-horizontal">
                <dt>
                    <!-- Detta är kattens namn -->
                    @Html.DisplayNameFor(model => model.Name)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Name)
                </dd>
                <dt>
                    <!-- Detta är kattens färg -->
                    @Html.DisplayNameFor(model => model.Color)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Color)
                </dd>
            </dl>
        </div>
    </div>
</div>

<div>
    <a asp-action="Index">Tillbaka till listan</a>
</div>

ASPNetMongoDB/Views/Cats/Edit.cshtml
@model Cat

@{
    ViewData["Title"] = "Redigera";
}

<h1>Redigera katt</h1>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Katt</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Id" />
        <!-- Detta är fältet där du kan ändra kattens namn -->
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>

        <!-- Detta är fältet där du kan ändra kattens färg -->
        <div class="form-group">
            <label asp-for="Color" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Color" class="form-control" />
                <span asp-validation-for="Color" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Tillbaka till listan</a>
</div>

ASPNetMongoDB/Views/Cats/Index.cshtml
@model IEnumerable<ASPNetMongoDB.Models.Cat>

@{
    ViewData["Title"] = "Kattlista";
}

<h1>Kattlista</h1>

<p>
    <a asp-action="Create">Skapa ny</a>
</p>
<table id="catto" class="display" style="width:100%">
    <thead>
        <tr>
            <th>
                <!-- Detta är namnet på katten -->
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                <!-- Detta är färgen på katten -->
                @Html.DisplayNameFor(model => model.Color)
            </th>
            <th>
                Verktyg
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Color)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Redigera</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Radera</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<script>
    $(document).ready(function () {
        $('#catto').DataTable();
    });
</script>

ASPNetMongoDB/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Detta projekt kom till en alldeles för sen natt, med hjälp av ChatGPT</p>
    <p>Projektet skapades för CLO22 av Marcus Medina, Campus Mölndal, 2022</p>
</div>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p><center>=^..^=</center></p>

ASPNetMongoDB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASPNetMongoDB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ASPNetMongoDB.styles.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASPNetMongoDB</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cats" asp-action="Index">My Cats</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ASPNetMongoDB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <link rel="stylesheet" type="text/css" href="~/lib/Datatables/datatables.min.css" />
    <script type="text/javascript" src="~/lib/Datatables/datatables.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>